import MeromorphicFunctionsSeveralComplexVariablesLemmaCanonicalLaneLean.Basic
import MeromorphicFunctionsSeveralComplexVariablesLemmaCanonicalLaneLean.SourcePackage
import MeromorphicFunctionsSeveralComplexVariablesLemmaCanonicalLaneLean.SourceDependencies
import MeromorphicFunctionsSeveralComplexVariablesLemmaCanonicalLaneLean.Formalization
import MeromorphicFunctionsSeveralComplexVariablesLemmaCanonicalLaneLean.ReviewerBridge
import MeromorphicFunctionsSeveralComplexVariablesLemmaCanonicalLaneLean.TheoremStatement
import MeromorphicFunctionsSeveralComplexVariablesLemmaCanonicalLaneLean.MathlibObjects
import MeromorphicFunctionsSeveralComplexVariablesLemmaCanonicalLaneLean.AdmissibleClass
import MeromorphicFunctionsSeveralComplexVariablesLemmaCanonicalLaneLean.Projection
import MeromorphicFunctionsSeveralComplexVariablesLemmaCanonicalLaneLean.BridgeLemmas
import MeromorphicFunctionsSeveralComplexVariablesLemmaCanonicalLaneLean.GateLemmas
import MeromorphicFunctionsSeveralComplexVariablesLemmaCanonicalLaneLean.FinalTheorem
import MeromorphicFunctionsSeveralComplexVariablesLemmaCanonicalLaneLean.ComplexManifold
import MeromorphicFunctionsSeveralComplexVariablesLemmaCanonicalLaneLean.MeromorphicFunction
import MeromorphicFunctionsSeveralComplexVariablesLemmaCanonicalLaneLean.SeveralComplexVariables
import MeromorphicFunctionsSeveralComplexVariablesLemmaCanonicalLaneLean.CousinProblems
import MeromorphicFunctionsSeveralComplexVariablesLemmaCanonicalLaneLean.CoherentSheaves
import MeromorphicFunctionsSeveralComplexVariablesLemmaCanonicalLaneLean.ComplexStructure
import MeromorphicFunctionsSeveralComplexVariablesLemmaCanonicalLaneLean.DecompositionTheorem
import MeromorphicFunctionsSeveralComplexVariablesLemmaCanonicalLaneLean.AdmissibleClassFoundation

namespace HautevilleHouse
namespace MeromorphicFunctionsSeveralComplexVariablesLemmaCanonicalLaneLean

def packageName : String := "MeromorphicFunctionsSeveralComplexVariablesLemmaCanonicalLaneLean"

end MeromorphicFunctionsSeveralComplexVariablesLemmaCanonicalLaneLean
end HautevilleHouse